DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS bears;
DROP TABLE IF EXISTS monitors;

CREATE TABLE cats (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    weight TEXT,
    age INT CHECK (age > 0)
);

CREATE TABLE bears (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    weight TEXT,
    scary BOOLEAN NOT NULL
);

CREATE TABLE monitors (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    size INTEGER NOT NULL,
    sick BOOLEAN NOT NULL

);
